#!/bin/csh -f

# ;***************************************************************************************************
# ;* FILE Name					: RUN_LN22FDX_PM
# ;***************************************************************************************************

# v0.1 - <muheim@ee.ethz.ch> - Tue Aug 18 14:17:20 CEST 2020
# - copy from /usr/pack/gf-22-kgf/gf/pdk-22FDX-EXT-V1.0_0.0/DFM/DRCplus/Calibre/PM/RUN_LN22FDX_PM RUN_LN22FDX_PM-EXT-example
# - add loading of the .setPDK.csh
# - change user setting value 
# - add if PROJECT_NAME not empty
# - add calibre-2024.4 befor calibre cale
# v0.2 - <zerun@ethz.ch> - Wed  3 Jan 15:18:29 CET 2024
# - copy from /usr/pack/gf-22-kgf/gf/pdk-22FDX-PLUS-V1.0_2.2/DFM/DRCplus/Calibre/PM/RUN_LN22FDX_PM
# - $MGC_HOME/bin/tclsh to calibre-2024.4 tclsh
#

source  ../../.setPDK.csh

# --------------------------------------------------------------------------------
#   user setting value : You have to fill out these variables for stand-alone mode
# --------------------------------------------------------------------------------

setenv	DRCPLUS_MODE 			"BATCH" 				;# Specifies which mode to run. Set to to BATCH (run as BATCH) OR GUI (Calibre GUI run) OR VARS (Source variables only). Default is: BATCH. Note that for "VARS" mode, you will need to source the file (not run it) 

setenv	TECHDIR_DFM_DRCPLUS		"$PDK_HOME/DFM/DRCplus/Calibre/PM/"	;# Specifies the path of standard run set. i.e. $GF_PDK_HOME/DFM/DRCPLUS/Calibre/PM

setenv	PROJECT_NAME			""					;# Specifies the title name					
setenv	LAYOUT_SYSTEM			"GDSII"				        ;# GDSII, OASIS					
setenv	LAYOUT_PATH                     "../drc/chip.gds.gz"			;# Specifies the path and gds name of the layout design file						
setenv	LAYOUT_PRIMARY			"*"					;# Top cell name						
setenv  RUN_PATTERNS    		"LV1"					;# Specify to ALL to run all patterns OR LV1 to run Level1 patterns only OR LV2 to run Level2 patterns only
setenv	OUTPUT_DIR			"."					;# Specifies the path of output results.						   
setenv  RUN_METHOD			"LOCAL"					;# For running at customer set to "LOCAL"    			
setenv  CPU_COUNT			"16"					;# Specifies the cpu count for job    					

#Enable LVL2 scoring
setenv	TECHDIR_DFM_SIGNOFF ""	                                ;# Specifies the path of standard run set. i.e. $GF_PDK_HOME/DFM/SIGN-OFF_Wrapper
setenv 	PM_RULE_SCORING 	        "NO"				        ;# Generates the scoring report

#Enable markesrs for layout-based fixing. See DFM Yield Enhancement Suite(YES) tool.
setenv MARKER_FIX "NO"; #<NO/YES>

#Enable machine learning rule.
setenv ENABLE_ML "YES"; #<NO/YES>
setenv PA2_FLOW	 "NO" ; #<NO|YES>
# -----------------------------------------------------------------------------
#   environment setting value : Don't edit in lines below
# -----------------------------------------------------------------------------

if ($DRCPLUS_MODE != "BATCH" && $DRCPLUS_MODE != "GUI" && $DRCPLUS_MODE != "VARS") then
    echo "ERROR: DRCPLUS_MODE is set to wrong value. Pleause use one of the allowed values of (BATCH | GUI | VARS)."
    exit
endif

if ( ! -e $TECHDIR_DFM_DRCPLUS ) then
    echo "ERROR : THERE IS NO STANDARD RUNSET FOR PM ($TECHDIR_DFM_DRCPLUS)"
	exit
endif

if ( $PROJECT_NAME == "" ) then
    echo "ERROR : THE PROJECT_NAME IS NOT SET"
	exit
endif

# To overcome DRC / DFM Summary count mismatch from Calibre 2017.4 onwards
setenv CALIBRE_INCLUDE_DFM_RESULTS 1

# To enable Virtuoso PDK->DFM pull down menu
setenv  TECHDIR_DFM_DRCPLUS_CAL                 $TECHDIR_DFM_DRCPLUS


if ($DRCPLUS_MODE == "VARS") then 

setenv	PM_LAYERS_MAPPING_FILE			$TECHDIR_DFM_DRCPLUS/Include/22FDX_Layermap.svrf

setenv	PM_LIBRARY_FILE1			$TECHDIR_DFM_DRCPLUS/Include/Library/PM.M1.CB.svrf
setenv	PM_LIBRARY_FILE2		        $TECHDIR_DFM_DRCPLUS/Include/Library/PM.M2.AY.fix.svrf
setenv	PM_LIBRARY_FILE3			$TECHDIR_DFM_DRCPLUS/Include/Library/PM_M2_Vx_C_x_fix.svrf
setenv	PM_LIBRARY_FILE4			$TECHDIR_DFM_DRCPLUS/Include/Library/PMGEN_M2_Vx_C_x_fix.svrf
setenv	PM_LIBRARY_FILE5			$TECHDIR_DFM_DRCPLUS/Include/Library/PM_Mx_C_x.svrf
setenv	PM_LIBRARY_FILE6			$TECHDIR_DFM_DRCPLUS/Include/Library/PM_Mx_C_x_2.svrf
setenv	PM_LIBRARY_FILE7			$TECHDIR_DFM_DRCPLUS/Include/Library/PM_Mx_C_x_tmp.svrf
setenv	PM_LIBRARY_FILE8			$TECHDIR_DFM_DRCPLUS/Include/Library/PM_Mx_C_x_3.svrf
setenv	PM_LIBRARY_FILE9			$TECHDIR_DFM_DRCPLUS/Include/Library/PM_Mx_C_x_4.svrf
setenv	PM_LIBRARY_FILE10			$TECHDIR_DFM_DRCPLUS/Include/Library/PM_M2_V1_C_5_ML.svrf
setenv	PM_LIBRARY_FILE11			$TECHDIR_DFM_DRCPLUS/Include/Library/PM_M1_C_x.svrf
setenv  PM_LIBRARY_FILE12			$TECHDIR_DFM_DRCPLUS/Include/Library/PM_M2_C_2.svrf

setenv  RDB_DIR_PM				${OUTPUT_DIR}/rdb/${PROJECT_NAME}
setenv  OUTPUT_RDB_PM				${RDB_DIR_PM}/${PROJECT_NAME}_PM.rdb
setenv  OUTPUT_RDB_PM_lv2			${RDB_DIR_PM}/${PROJECT_NAME}_PM_LV2.rdb
setenv  OUTPUT_RDB_PM_ALL			${RDB_DIR_PM}/${PROJECT_NAME}_PM_ALL.rdb
setenv  OUTPUT_SUM_PM				${RDB_DIR_PM}/${PROJECT_NAME}_PM.sum
setenv  GUI_RUN_DIR				${OUTPUT_DIR}/GUI_RUN
    echo "DRCPLUS_MODE is set to VARS. Variables are initialized only with no run."
	exit
endif

#===============================================================================
#> PM :: PM Execution
#===============================================================================

if ($DRCPLUS_MODE == "GUI") then 
    echo "DRCPLUS_MODE is set to GUI. Variables are initialized then running through Calibre GUI with the runset file."
setenv  GUI_RUN_DIR				${OUTPUT_DIR}/GUI_RUN
mkdir -p  ${GUI_RUN_DIR}

calibre-2024.4 calibre -gui -drc -nowait -runset RUN_LN22FDX_PM_GUI.runset ;# Please make sure that LAYOUT SYSTEM is set to correct value of OASIS or GDSII systems. Please use full paths.

	exit
endif


if ( $DRCPLUS_MODE == "BATCH" ) then 
    echo "DRCPLUS_MODE is set to BATCH. Variables are initialized then running in batch mode."
setenv  RDB_DIR_PM				${OUTPUT_DIR}/rdb/${PROJECT_NAME}
if ( -e ${RDB_DIR_PM} ) then
    echo "WARNING : PROJECT ${PROJECT_NAME} EXISTS FROM BEFORE. RENAMING EXISTING PROJECT TO ${PROJECT_NAME}_BKUP."
	mv ${RDB_DIR_PM} ${RDB_DIR_PM}_BKUP
	mv ${OUTPUT_DIR}/log_file/${PROJECT_NAME}_PM.log ${OUTPUT_DIR}/log_file/${PROJECT_NAME}_PM.log_BKUP
endif

mkdir -p  ${RDB_DIR_PM} ${OUTPUT_DIR}/log_file

if ($RUN_METHOD == LSF) then
        # for LSF run 

else if ($RUN_METHOD == LOCAL) then
	# for local run  : You have to fill out MGC variables for stand-alone mode

 calibre-2024.4 calibre -drc -hier -64 -nowait -hyper -turbo ${CPU_COUNT}  ${TECHDIR_DFM_DRCPLUS}/Include/LN22FDX_PM_MAIN.tvf | tee ${OUTPUT_DIR}/log_file/${PROJECT_NAME}_PM.log

else
    echo 'ERROR: Please set the variable "RUN_METHOD" to "LSF" or "LOCAL"'
endif

#===============================================================================
#> GF summary file
#===============================================================================

if ( ! -e ${RDB_DIR_PM}/${PROJECT_NAME}_PM.sum ) then
    echo "ERROR : THERE IS NO SUMMARY FILE GENERATED. PLEASE CHECK YOUR RUN."
	exit
endif

calibre-2024.4 tclsh $TECHDIR_DFM_DRCPLUS/Include/generateGFsummary_Calibre.tclsh ${RDB_DIR_PM}/${PROJECT_NAME}_PM.sum

head -12 ${RDB_DIR_PM}/${PROJECT_NAME}_PM.sum_GFsummary
echo "==================================="
echo "PLEASE CHECK THE GF SUMMARY FILE '${RDB_DIR_PM}/${PROJECT_NAME}_PM.sum_GFsummary' FOR HIGH LEVEL SUMMARY."
echo ""
echo "Disclaimer:"
echo "-----------"
echo "Please refer to the rdb files '${RDB_DIR_PM}/${PROJECT_NAME}_PM*.rdb' for sign-off. GF summary file only contains brief statistics of the run/violations."
echo "==================================="

endif

#===============================================================================
#> PM rule scoring step
#===============================================================================
if ( ! -e ${RDB_DIR_PM}/${PROJECT_NAME}_PM.sum_GFsummary) then
    echo "WARNING : THERE IS NO GF SUMMARY FILE GENERATED. PLEASE CHECK YOUR RUN."
	exit
endif

if !($?PM_RULE_SCORING) then
setenv PM_RULE_SCORING "NO"
echo "WARNING: PM_RULE_SCORING SET TO NO. PM RULES WILL NOT BE SCORED."
endif 

if !($?MARKER_FIX) then
setenv MARKER_FIX "NO"
endif

if ($PM_RULE_SCORING ==  "YES") then 
### NEW INVOCATION from PDK v1.0_1.0 onward. ###
$TECHDIR_DFM_SIGNOFF/Include/computeScorePMrules  -l ${OUTPUT_DIR}/log_file/${PROJECT_NAME}_PM.log -s ${RDB_DIR_PM}/${PROJECT_NAME}_PM.sum_GFsummary -c ${RDB_DIR_PM}/${PROJECT_NAME}_drcplusReport.csv -t cal
endif

if !($?ENABLE_ML) then
setenv ENABLE_ML "YES"
endif

if !($?PA2_FLOW) then
setenv PA2_FLOW "NO"
endif
